// Generated by CoffeeScript 1.12.7
(function() {
  var Client;

  Client = (function() {
    Client.prototype.id = 0;

    function Client(transport) {
      this.transport = transport;
      if (!this.transport) {
        throw new Error('emptyTransport');
      }
    }

    Client.prototype.request = function(method, params, setId) {
      var req;
      if (setId == null) {
        setId = true;
      }
      req = {
        method: method,
        params: params,
        jsonrpc: '2.0'
      };
      if (setId) {
        req.id = ++this.id;
      }
      return req;
    };

    Client.prototype.notify = function(method, params) {
      var req;
      if (params == null) {
        params = [];
      }
      req = this.request(method, params, false);
      this.transport.send(req);
      return true;
    };

    Client.prototype.batch = function(methods, params, callback) {
      var i, j, len, method, req;
      req = [];
      for (i = j = 0, len = methods.length; j < len; i = ++j) {
        method = methods[i];
        req.push(this.request(method, params[i]));
      }
      return this.transport.send(req, callback);
    };

    Client.prototype.invoke = function(method, params, callback) {
      var req;
      req = this.request(method, params);
      return this.transport.send(req, callback);
    };

    return Client;

  })();

  module.exports = Client;

}).call(this);
