// Generated by CoffeeScript 1.12.7
(function() {
  var abstract, invalidParams, invalidRequest, methodNotFound, parseError;

  abstract = function(message, code, id) {
    if (code == null) {
      code = -32099;
    }
    if (id == null) {
      id = null;
    }
    return {
      id: id,
      jsonrpc: '2.0',
      error: {
        code: code,
        message: message
      }
    };
  };

  parseError = function(id) {
    if (id == null) {
      id = null;
    }
    return abstract('ParseError', -32700, id);
  };

  invalidRequest = function(id) {
    if (id == null) {
      id = null;
    }
    return abstract('InvalidRequest', -32600, id);
  };

  methodNotFound = function(id) {
    if (id == null) {
      id = null;
    }
    return abstract('MethodNotFound', -32601, id);
  };

  invalidParams = function(id) {
    if (id == null) {
      id = null;
    }
    return abstract('InvalidParams', -32602, id);
  };

  exports.abstract = abstract;

  exports.parseError = parseError;

  exports.invalidRequest = invalidRequest;

  exports.methodNotFound = methodNotFound;

  exports.invalidParams = invalidParams;

}).call(this);
