// Generated by CoffeeScript 1.12.7
(function() {
  module.exports = function(server) {
    return function(socket, next) {
      socket.on("message", function(data) {
        var req;
        req = socket.request;
        req.client_ip = req.headers['x-forwarded-for'] || req.connection.remoteAddress || '127.0.0.1';
        req.client_ip = req.client_ip.replace('::ffff:', '');
        return server.handleCall(data, req, function(answer) {
          return socket.send(JSON.stringify(answer));
        });
      });
      return next();
    };
  };

}).call(this);
